# WeatherPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import sys 
sys.path.append('..')
import os
# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

638

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

> **HINT:** The OpenWeatherMap API only allows 60 calls per minute under their free plan. Try using `time.sleep(60)` after each set of 50 cities to avoid API errors due to large calls.

In [11]:
#save config
base_url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key 


name = []
number = []
lat = []
lon = []
maxt = []
hum = []
clds = []
ws = []
country = []
date = []

#loop through city and request data on each one
index = 0
group = 1
for city in cities[:53]:
    #rate limit on api calls
    index +=1
    if index ==51:
        index = 0
        group += 1
        time.sleep(60)
    #http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID==Atlanta
    #base_url -------------------------------------------------------------------------------------------
    city_url = f"{base_url}&q={city.replace(' ', '+')}"
    response = requests.get(city_url).json()
#append results to list placeholders
    try:
        number.append(response['id'])
        lat.append(response['coord']['lat'])
        lon.append(response['coord']['lon'])
        maxt.append(response['main']['temp_max'])
        hum.append(response['main']['humidity'])
        clds.append(response['clouds']['all'])
        ws.append(response['wind']['speed'])
        country.append(response['sys']['country'])
        date.append(response['dt'])
        name.append(response['name'])
        print(f"Processing Record {index} of set {group} for {city}, with city number {response['id']}")

    #alert when city is not found
    except KeyError:
        print("City not found.  Moving on...")
        pass

print('Data Processing Complete')

Processing Record 1 of set 1 for chokurdakh, with city number 2126123
Processing Record 2 of set 1 for grand gaube, with city number 934479
Processing Record 3 of set 1 for tuktoyaktuk, with city number 6170031
Processing Record 4 of set 1 for alice springs, with city number 2077895
Processing Record 5 of set 1 for chhabra, with city number 1274381
Processing Record 6 of set 1 for clarence town, with city number 2171465
Processing Record 7 of set 1 for avarua, with city number 4035715
Processing Record 8 of set 1 for yellowknife, with city number 6185377
Processing Record 9 of set 1 for banda aceh, with city number 1215502
Processing Record 10 of set 1 for castro, with city number 3466704
Processing Record 11 of set 1 for bluff, with city number 2206939
Processing Record 12 of set 1 for barrow, with city number 5880054
Processing Record 13 of set 1 for villa carlos paz, with city number 3832791
Processing Record 14 of set 1 for mataura, with city number 6201424
Processing Record 15 of set 1 for ushuaia, with city number 3833367
Processing Record 16 of set 1 for hobart, with city number 2163355
Processing Record 17 of set 1 for la libertad, with city number 3655131
Processing Record 18 of set 1 for puerto carreno, with city number 3671519
Processing Record 19 of set 1 for port alfred, with city number 964432
Processing Record 20 of set 1 for vostok, with city number 2013279
City not found.  Moving on...
Processing Record 22 of set 1 for erice, with city number 2524815
Processing Record 23 of set 1 for ylivieska, with city number 630768
Processing Record 24 of set 1 for paamiut, with city number 3421193
Processing Record 25 of set 1 for sitka, with city number 5557293
Processing Record 26 of set 1 for klaksvik, with city number 2618795
Processing Record 27 of set 1 for birao, with city number 240210
Processing Record 28 of set 1 for hithadhoo, with city number 1282256
Processing Record 29 of set 1 for cape town, with city number 3369157
Processing Record 30 of set 1 for praia, with city number 3374333
Processing Record 31 of set 1 for rikitea, with city number 4030556
Processing Record 32 of set 1 for thompson, with city number 6165406
Processing Record 33 of set 1 for leeton, with city number 2160413
Processing Record 34 of set 1 for banihal, with city number 1277297
Processing Record 35 of set 1 for rio grande, with city number 3451138
Processing Record 36 of set 1 for oktyabrskoye, with city number 515805
Processing Record 37 of set 1 for punta arenas, with city number 3874787
Processing Record 38 of set 1 for georgetown, with city number 1735106
Processing Record 39 of set 1 for san juan del sur, with city number 3616726
Processing Record 40 of set 1 for saldanha, with city number 3361934
Processing Record 41 of set 1 for dikson, with city number 1507390
Processing Record 42 of set 1 for iqaluit, with city number 5983720
Processing Record 43 of set 1 for albany, with city number 5106841
Processing Record 44 of set 1 for nikolskoye, with city number 546105
City not found.  Moving on...
Processing Record 46 of set 1 for jamestown, with city number 5122534
Processing Record 47 of set 1 for torbay, with city number 6167817
Processing Record 48 of set 1 for hay river, with city number 5972762
Processing Record 49 of set 1 for gamba, with city number 2400547
City not found.  Moving on...
Processing Record 0 of set 2 for tessalit, with city number 2449893
Processing Record 1 of set 2 for lebu, with city number 3883457
Processing Record 2 of set 2 for elmira, with city number 5116497
Data Processing Complete

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [12]:
#create dataframe out of above results

weather_dictionary = {
    "City": name,
    "Lat": lat,
    "Lon": lon,
    "Max Temp": maxt,
    "Humidity": hum,
    "Cloudiness": clds,
    "Wind Speed": ws,
    "Country": country,
    "Date": date
}

weat_data = pd.DataFrame(weather_dictionary)
weat_data

,City,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Chokurdakh,70.6333,147.9167,6.39,93,100,7.40,RU,1649974685
1,Grand Gaube,-20.0064,57.6608,78.39,74,19,10.00,MU,1649974685
2,Tuktoyaktuk,69.4541,-133.0374,-2.20,78,20,9.22,CA,1649974686
3,Alice Springs,-23.7000,133.8833,69.22,32,40,0.00,AU,1649974686
4,Chhabra,24.6667,76.8333,84.06,17,16,6.87,IN,1649974686
5,Clarence Town,-32.5833,151.7833,63.86,84,32,2.08,AU,1649974687
6,Avarua,-21.2078,-159.7750,82.45,74,88,4.61,CK,1649974687
7,Yellowknife,62.4560,-114.3525,24.30,56,75,9.22,CA,1649974688
8,Banda Aceh,5.5577,95.3222,80.19,80,91,1.79,ID,1649974688
9,Castro,-24.7911,-50.0119,58.32,95,18,5.99,BR,1649974688
10,Bluff,-46.6000,168.3333,55.80,75,11,11.32,NZ,1649974689
11,Barrow,71.2906,-156.7887,1.42,78,0,18.41,US,1649974689
12,Villa Carlos Paz,-31.4241,-64.4978,66.40,26,0,13.00,AR,1649974689
13,Mataura,-46.1927,168.8643,55.47,74,5,2.26,NZ,1649974690
14,Ushuaia,-54.8000,-68.3000,47.86,57,20,18.41,AR,1649974690
15,Hobart,-42.8794,147.3294,63.27,64,75,20.71,AU,1649974691
16,La Libertad,-2.2333,-80.9000,74.86,78,0,9.22,EC,1649974691
17,Puerto Carreño,6.1890,-67.4859,96.78,36,20,5.75,CO,1649974691
18,Port Alfred,-33.5906,26.8910,64.18,93,99,5.99,ZA,1649974692
19,Vostok,46.4856,135.8833,30.49,76,22,1.61,RU,1649974692
20,Erice,38.0370,12.5865,52.27,82,0,3.44,IT,1649974693
21,Ylivieska,64.0833,24.5500,33.89,95,100,5.23,FI,1649974693
22,Paamiut,61.9940,-49.6678,23.07,81,93,29.39,GL,1649974693
23,Sitka,57.0531,-135.3300,46.29,29,0,9.22,US,1649974694
24,Klaksvík,62.2266,-6.5890,45.52,91,100,30.33,FO,1649974694
25,Birao,10.2849,22.7882,85.77,12,51,3.76,CF,1649974694
26,Hithadhoo,-0.6000,73.0833,83.19,72,97,7.54,MV,1649974695
27,Cape Town,-33.9258,18.4232,59.88,75,75,13.80,ZA,1649974695
28,Praia,14.9215,-23.5087,70.34,73,20,12.66,CV,1649974695
29,Rikitea,-23.1203,-134.9692,77.83,69,27,17.36,PF,1649974696
30,Thompson,55.7435,-97.8558,15.96,48,75,23.02,CA,1649974696
31,Leeton,-34.5667,146.4000,63.43,55,96,4.52,AU,1649974696
32,Banihāl,33.4167,75.2000,51.71,64,25,4.79,IN,1649974697
33,Rio Grande,-32.0350,-52.0986,62.71,59,2,16.24,BR,1649974697
34,Oktyabr'skoye,43.0645,44.7417,37.35,93,78,6.71,RU,1649974697
35,Punta Arenas,-53.1500,-70.9167,50.11,66,75,9.22,CL,1649974481
36,George Town,5.4112,100.3354,78.73,99,20,4.61,MY,1649974698
37,San Juan del Sur,11.2529,-85.8705,88.02,62,20,6.91,NI,1649974698
38,Saldanha,-33.0117,17.9442,60.49,68,5,19.80,ZA,1649974698
39,Dikson,73.5069,80.5464,15.76,93,100,6.42,RU,1649974699
40,Iqaluit,63.7506,-68.5145,-0.31,70,0,19.57,CA,1649974699
41,Albany,42.6001,-73.9662,58.59,78,100,14.00,US,1649974402
42,Nikolskoye,59.7035,30.7861,38.88,99,100,2.57,RU,1649974699
43,Jamestown,42.0970,-79.2353,54.52,18,0,13.80,US,1649974700
44,Torbay,47.6666,-52.7314,35.28,78,20,13.80,CA,1649974519
45,Hay River,60.8156,-115.7999,30.18,34,20,6.91,CA,1649974700
46,Gamba,-2.6500,10.0000,75.72,92,100,4.32,GA,1649974701
47,Tessalit,20.1986,1.0114,83.25,8,0,8.28,ML,1649974761
48,Lebu,-37.6167,-73.6500,55.08,78,1,6.91,CL,1649974568
49,Elmira,42.0898,-76.8077,57.81,47,40,16.11,US,1649974762

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [ ]:
#  Get the indices of cities that have humidity over 100%.

In [ ]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression